=== sjanedam/LenguajeMarcasPHP/xml/Actividad4.dtd
<!ELEMENT listafacturas (factura+)>
<!ELEMENT factura (emisor, pagador,importe)>
<!ELEMENT emisor  (nombre, volumenventas?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT volumenventas (#PCDATA)>
<!ELEMENT pagador (nombre, volumenventas?)>
<!ELEMENT importe (#PCDATA)>
<!ATTLIST factura fecha CDATA #IMPLIED>
<!ATTLIST emisor cif CDATA #REQUIRED>
<!ATTLIST pagador cif CDATA #REQUIRED>

=== sjanedam/LenguajeMarcasPHP/xml/Actividad4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listafacturas  SYSTEM "Actividad4.dtd"> 

<listafacturas>
  <factura fecha="22/02/2022">
    <emisor cif="A-48265169">
      <nombre>BBVA</nombre>
      <volumenventas/>
    </emisor>
    <pagador cif="A-48265169">
      <nombre>BBVA</nombre>
    </pagador>
    <importe>50€</importe>
  </factura>
</listafacturas>
